// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import Theming from "@/Theme/Theming";
// import "./globals.css";
// import Footer from "@/app/Footer/page"
// import Header from "@/app/Header/page";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Abhilash.Sarangi",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body >
//       <Theming>
//       <Header />
//         {children}
//       <Footer/>
//       </Theming>
//       </body>
//     </html>
//   );
// }

import Theming from "@/Theme/Theming";
import "./globals.css";
import Headerpage from "@/app/Header/page";
import Footerpage from "@/app/Footer/page";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Theming>
          <Headerpage />
          {children}
          <Footerpage />
        </Theming>
      </body>
    </html>
  );
}